name: Build ReveFlex

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 配置 Theos 编译环境
        uses: Randomblock1/theos-action@v1

      - name: 开始编译插件
        run: make package

      - name: 上传编译成品 (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ReveFlex-Tweak-Package
          path: packages/*.deb
